# Generated by Django 4.2.5 on 2023-09-13 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cursos',
            table='evento',
        ),
    ]
